#!/bin/bash 
#######################################################################################
# H0zTyL - R. Seaverns - K0NXT3D - 2021                                               #
# Random User Agent Enabled                                                           #
# Use With Proxychains                                                                #                            
#     --delete-after \ Will Delete all files automatically and save local file space. #
#     --mirror \ Will Download the entire site (Default)                              #
#######################################################################################
urlfile='files/urls.txt'
uafile='files/user-agents.txt'
domfile='files/random-domains.txt'
agent=$(shuf -n 1 $uafile)
domain=$(shuf -n 1 $domfile)
art='banner.txt'

input=$art
while IFS= read -r line
do
  echo "$line"
done < "$input"
sleep 2
mkdir BotFiles
cat $urlfile | while read URL; do
proxychains='bash proxychains'
$proxychains wget -P BotFiles/ \
     -rkp -e robots=off \
     --header="Accept: text/html" \
     --user-agent="$agent" \
     --referer="$domain" \
     --mirror \
     -l 0 \
     --page-requisites \
     --restrict-file-names=windows \
     --adjust-extension \
     --domains www.$URL \
     --no-parent \
     --wait=0 \
         www.$URL
done
rm -r BotFiles

# Finsh and Exit
exit
# Loop Infinitely
#./$(basename $0) && exit
